"""Statik referans verileri: kulüp adı eşlemeleri, bayrak kodları, büyük takımlar.

Bu veriler eski `functions.py` ve `guessingEndpoints.py` dosyalarından taşındı;
içerikleri değiştirilmedi, yalnızca tek bir modülde toplandı.
"""

LOGO_MAPPINGS = {'AFC Bournemouth': 'Bournemouth',
 'Nottingham Forest': 'Nottingham',
 'Wolverhampton Wanderers': 'Wolves',
 'Brighton & Hove Albion': 'Brighton',
 'West Ham United': 'West Ham',
 'Tottenham Hotspur': 'Tottenham',
 'Newcastle United': 'Newcastle',
 'Leicester City': 'Leicester',
 'Leeds United': 'Leeds',
 'Ipswich Town': 'Ipswich',
 'Bayer 04 Leverkusen': 'Bayer Leverkusen',
 'TSG 1899 Hoffenheim': 'Hoffenheim',
 'VfL Bochum': 'Bochum',
 '1.FSV Mainz 05': 'Mainz',
 '1.FC Union Berlin': 'Union Berlin',
 'VfB Stuttgart': 'Stuttgart',
 'Borussia Monchengladbach': 'Gladbach',
 'Eintracht Frankfurt': 'Frankfurt',
 'Paris Saint-Germain': 'PSG',
 'AS Monaco': 'Monaco',
 'Olympique Marseille': 'Marseille',
 'Olympique Lyon': 'Lyon',
 'Stade Rennais FC': 'Rennes',
 'OGC Nice': 'Nice',
 'RC Lens': 'Lens',
 'LOSC Lille': 'Lille',
 'Inter Milan': 'Inter',
 'AC Milan': 'Milan',
 'AS Roma': 'Roma',
 'SS Lazio': 'Lazio',
 'SSC Napoli': 'Napoli',
 'Atalanta BC': 'Atalanta',
 'Juventus FC': 'Juventus',
 'ACF Fiorentina': 'Fiorentina',
 'Torino FC': 'Torino',
 'Udinese Calcio': 'Udinese',
 'Hellas Verona': 'Verona',
 'US Lecce': 'Lecce',
 'FC Empoli': 'Empoli',
 'Genoa CFC': 'Genoa',
 'Cagliari Calcio': 'Cagliari',
 'Athletic Bilbao': 'Athletic Club',
 'Atletico de Madrid': 'Atletico Madrid',
 'RCD Mallorca': 'Mallorca',
 'CA Osasuna': 'Osasuna',
 'Rayo Vallecano': 'Rayo',
 'Real Betis Balompie': 'Betis',
 'Real Sociedad': 'Sociedad',
 'Sevilla FC': 'Sevilla',
 'Valencia CF': 'Valencia',
 'Villarreal CF': 'Villarreal',
 'RC Celta de Vigo': 'Celta',
 'Getafe CF': 'Getafe',
 'Girona FC': 'Girona',
 'Cadiz CF': 'Cadiz',
 'UD Almeria': 'Almeria',
 'Granada CF': 'Granada',
 'Deportivo Alaves': 'Alaves',
 'UD Las Palmas': 'Las Palmas',
 'Sivasspor': 'Sivasspor',
 'Pendikspor': 'Pendikspor',
 'Rams Basaksehir': 'Basaksehir',
 'Istanbul Basaksehir FK': 'Basaksehir',
 'MKE Ankaragucu': 'Ankaragucu',
 'Fatih Karagumruk': 'Karagumruk',
 'Gaziantep FK': 'Gaziantep FK',
 'Hatayspor': 'Hatayspor',
 'Alanyaspor': 'Alanyaspor',
 'Antalyaspor': 'Antalyaspor',
 'Kasimpasa': 'Kasimpasa',
 'Caykur Rizespor': 'Rizespor',
 'Adana Demirspor': 'Adana Demirspor',
 'Istanbulspor': 'Istanbulspor',
 'Samsunspor': 'Samsunspor',
 'Konyaspor': 'Konyaspor',
 'Kayserispor': 'Kayserispor'}

FLAG_MAPPINGS = {'DR Congo': 'CD',
 'Cape Verde': 'CV',
 'Bosnia-Herzegovina': 'BA',
 'Korea, South': 'KR',
 'South Korea': 'KR',
 'North Korea': 'KP',
 'Korea, North': 'KP',
 'St. Lucia': 'LC',
 'St. Kitts & Nevis': 'KN',
 'Neukaledonien': 'NC',
 'New Caledonia': 'NC',
 'Southern Sudan': 'SS',
 'South Sudan': 'SS',
 'Tahiti': 'PF',
 'Chinese Taipei': 'TW',
 'Taiwan': 'TW',
 'Turkey': 'TR',
 'Türkiye': 'TR',
 "Cote d'Ivoire": 'CI',
 'Ivory Coast': 'CI'}

BIG_TEAMS = {'GB1': ['Manchester City',
         'Arsenal FC',
         'Liverpool FC',
         'Manchester United',
         'Chelsea FC',
         'Tottenham Hotspur'],
 'ES1': ['Real Madrid', 'FC Barcelona', 'Atletico de Madrid', 'Sevilla FC'],
 'IT1': ['Inter Milan', 'AC Milan', 'Juventus FC', 'SSC Napoli', 'AS Roma'],
 'L1': ['Bayern Munich', 'Borussia Dortmund', 'Bayer 04 Leverkusen', 'RB Leipzig'],
 'FR1': ['Paris Saint-Germain', 'Olympique Marseille', 'AS Monaco', 'Olympique Lyon'],
 'TR1': ['Galatasaray', 'Fenerbahce', 'Besiktas JK', 'Trabzonspor']}

BANNED_KEYWORDS = ['Basketbol',
 'Basketball',
 'B.C.',
 'B.K.',
 'Basket',
 'Voleybol',
 'Volleyball',
 'Hentbol',
 'Handball']

TSDB_SEARCH = {'Arsenal FC': 'Arsenal',
 'Chelsea FC': 'Chelsea',
 'Liverpool FC': 'Liverpool',
 'Manchester City': 'Man City',
 'Manchester United': 'Manchester United',
 'Tottenham Hotspur': 'Tottenham Hotspur',
 'Newcastle United': 'Newcastle United',
 'West Ham United': 'West Ham United',
 'Aston Villa': 'Aston Villa',
 'Brighton & Hove Albion': 'Brighton & Hove Albion',
 'Crystal Palace': 'Crystal Palace',
 'Everton FC': 'Everton',
 'Wolverhampton Wanderers': 'Wolves',
 'AFC Bournemouth': 'Bournemouth',
 'Nottingham Forest': 'Nottingham Forest',
 'Brentford FC': 'Brentford',
 'Fulham FC': 'Fulham',
 'Leicester City': 'Leicester City',
 'Ipswich Town': 'Ipswich Town',
 'Southampton FC': 'Southampton',
 'Watford FC': 'Watford',
 'Burnley FC': 'Burnley',
 'Leeds United': 'Leeds United',
 'Real Madrid': 'Real Madrid',
 'FC Barcelona': 'Barcelona',
 'Atletico de Madrid': 'Atletico Madrid',
 'Sevilla FC': 'Sevilla',
 'Real Sociedad': 'Real Sociedad',
 'Real Betis Balompie': 'Real Betis',
 'Villarreal CF': 'Villarreal',
 'Athletic Bilbao': 'Athletic Bilbao',
 'Valencia CF': 'Valencia',
 'Getafe CF': 'Getafe',
 'CA Osasuna': 'Osasuna',
 'RC Celta de Vigo': 'Celta Vigo',
 'Rayo Vallecano': 'Rayo Vallecano',
 'Girona FC': 'Girona',
 'RCD Mallorca': 'Mallorca',
 'CD Leganes': 'Leganes',
 'UD Las Palmas': 'Las Palmas',
 'Cadiz CF': 'Cadiz',
 'Albacete Balompie': 'Albacete',
 'CD Numancia': 'Numancia',
 'CD Tenerife': 'Tenerife',
 'CF Extremadura (- 2010)': 'Extremadura',
 'CP Merida': 'Merida',
 'CD Logrones': 'CD Logroñés',
 'Deportivo Alaves': 'Alaves',
 'Deportivo de La Coruna': 'Deportivo',
 'Gimnastic de Tarragona': 'Gimnastic',
 'Hercules CF': 'Hercules',
 'Bayern Munich': 'Bayern Munich',
 'Borussia Dortmund': 'Dortmund',
 'RB Leipzig': 'RB Leipzig',
 'Bayer 04 Leverkusen': 'Bayer Leverkusen',
 'Eintracht Frankfurt': 'Eintracht Frankfurt',
 'VfB Stuttgart': 'Stuttgart',
 'VfL Wolfsburg': 'Wolfsburg',
 'SC Freiburg': 'Freiburg',
 'Borussia Monchengladbach': 'Gladbach',
 '1.FC Union Berlin': 'Union Berlin',
 '1.FSV Mainz 05': 'Mainz',
 'TSG 1899 Hoffenheim': 'Hoffenheim',
 'FC Augsburg': 'Augsburg',
 'SV Werder Bremen': 'Werder Bremen',
 'VfL Bochum': 'Bochum',
 'FC Schalke 04': 'Schalke',
 'Inter Milan': 'Inter Milan',
 'AC Milan': 'AC Milan',
 'Juventus FC': 'Juventus',
 'SSC Napoli': 'Napoli',
 'AS Roma': 'Roma',
 'SS Lazio': 'Lazio',
 'ACF Fiorentina': 'Fiorentina',
 'Atalanta BC': 'Atalanta',
 'Torino FC': 'Torino',
 'Bologna FC 1909': 'Bologna',
 'Genoa CFC': 'Genoa',
 'Cagliari Calcio': 'Cagliari',
 'Udinese Calcio': 'Udinese',
 'US Lecce': 'Lecce',
 'FC Empoli': 'Empoli',
 'Hellas Verona': 'Verona',
 'US Sassuolo': 'Sassuolo',
 'Como 1907': 'Como',
 'Parma Calcio 1913': 'Parma',
 'Venezia FC': 'Venezia',
 'Paris Saint-Germain': 'Paris SG',
 'Olympique Marseille': 'Marseille',
 'Olympique Lyon': 'Lyon',
 'AS Monaco': 'Monaco',
 'LOSC Lille': 'Lille',
 'Stade Rennais FC': 'Rennes',
 'OGC Nice': 'Nice',
 'RC Lens': 'Lens',
 'FC Nantes': 'Nantes',
 'Le Havre AC': 'Le Havre',
 'Galatasaray': 'Galatasaray',
 'Fenerbahce': 'Fenerbahce',
 'Besiktas JK': 'Besiktas',
 'Trabzonspor': 'Trabzonspor',
 'SL Benfica': 'Benfica',
 'FC Porto': 'Porto',
 'Sporting CP': 'Sporting CP',
 'Ajax Amsterdam': 'Ajax',
 'PSV Eindhoven': 'PSV',
 'Feyenoord Rotterdam': 'Feyenoord',
 'Celtic FC': 'Celtic',
 'Rangers FC': 'Rangers',
 'Club Brugge KV': 'Club Brugge',
 'RSC Anderlecht': 'Anderlecht',
 'Stoke City': 'Stoke City',
 'Hull City': 'Hull City',
 'Sunderland AFC': 'Sunderland',
 'Derby County': 'Derby County',
 'Sheffield United': 'Sheffield Utd',
 'Luton Town': 'Luton Town',
 'Hamburger SV': 'Hamburg',
 'Hertha BSC': 'Hertha Berlin',
 'Fortuna Dusseldorf': 'Fortuna Dusseldorf',
 'FC St. Pauli': 'St Pauli',
 'Holstein Kiel': 'Holstein Kiel',
 'Espanyol Barcelona': 'Espanyol',
 'RCD Espanyol Barcelona': 'Espanyol',
 'Granada CF': 'Granada',
 'Elche CF': 'Elche',
 'Huddersfield Town': 'Huddersfield Town',
 'CSKA Moscow': 'CSKA Moscow',
 'Spartak Moscow': 'Spartak Moscow',
 'Dynamo Moscow': 'Dynamo Moscow',
 'Lokomotiv Moscow': 'Lokomotiv Moscow',
 'Shakhtar Donetsk': 'Shakhtar Donetsk',
 'Dynamo Kyiv': 'Dynamo Kyiv',
 'Olympiacos Piraeus': 'Olympiakos',
 'PAOK Thessaloniki FC': 'PAOK',
 'Panathinaikos FC': 'Panathinaikos',
 'AEK Athens FC': 'AEK Athens',
 'FC Copenhagen': 'FC Copenhagen',
 'FC Midtjylland': 'Midtjylland',
 'Clermont Foot 63': 'Clermont',
 'ESTAC Troyes': 'Troyes',
 'RC Strasbourg Alsace': 'Strasbourg',
 'Angers SCO': 'Angers',
 'FC Metz': 'Metz',
 'Toulouse FC': 'Toulouse',
 'Montpellier HSC': 'Montpellier',
 'Stade Reims': 'Reims',
 'Standard Liege': 'Standard Liege',
 'KAA Gent': 'Gent',
 'AZ Alkmaar': 'AZ Alkmaar',
 'FC Twente': 'Twente',
 'FC Utrecht': 'FC Utrecht',
 'Frosinone Calcio': 'Frosinone',
 'Birmingham City': 'Birmingham City',
 'Blackburn Rovers': 'Blackburn Rovers',
 'Bolton Wanderers': 'Bolton Wanderers',
 'Bristol City': 'Bristol City',
 'Coventry City': 'Coventry City',
 'Blackpool FC': 'Blackpool',
 'Swansea City': 'Swansea City',
 'Norwich City': 'Norwich City',
 'Queens Park Rangers': 'Queens Park Rangers',
 'West Bromwich Albion': 'West Bromwich Albion',
 'Wigan Athletic': 'Wigan Athletic',
 'Sheffield Wednesday': 'Sheffield Wednesday',
 'Portsmouth FC': 'Portsmouth',
 'Plymouth Argyle': 'Plymouth',
 'Preston North End': 'Preston',
 'Barnsley FC': 'Barnsley',
 'Charlton Athletic': 'Charlton Athletic',
 'Millwall FC': 'Millwall',
 'Doncaster Rovers': 'Doncaster',
 'Rotherham United': 'Rotherham',
 'Benevento Calcio': 'Benevento',
 'Brescia Calcio': 'Brescia',
 'UC Sampdoria': 'Sampdoria',
 'US Cremonese': 'Cremonese',
 'SC Braga': 'Braga',
 'FK Krasnodar': 'Krasnodar',
 'FK Rostov': 'Rostov',
 'Rubin Kazan': 'Rubin Kazan',
 'Hannover 96': 'Hannover',
 'SV Darmstadt 98': 'Darmstadt',
 'FC Ingolstadt 04': 'Ingolstadt',
 'Karlsruher SC': 'Karlsruhe',
 '1.FC Heidenheim 1846': 'Heidenheim',
 '1.FC Kaiserslautern': 'Kaiserslautern',
 '1.FC Nuremberg': 'Nurnberg',
 'FC Girondins Bordeaux': 'Bordeaux',
 'AC Monza': 'Monza',
 'Istanbul Basaksehir FK': 'Istanbul Basaksehir',
 'Adana Demirspor': 'Adana Demirspor',
 'Alanyaspor': 'Alanyaspor',
 'Antalyaspor': 'Antalyaspor',
 'Gaziantep FK': 'Gaziantep FK',
 'Kayserispor': 'Kayserispor',
 'Konyaspor': 'Konyaspor',
 'Hatayspor': 'Hatayspor',
 'Sivasspor': 'Sivasspor',
 'Samsunspor': 'Samsunspor',
 'Pendikspor': 'Pendikspor',
 'Rizespor': 'Caykur Rizespor',
 'Caykur Rizespor': 'Caykur Rizespor',
 'AJ Auxerre': 'Auxerre',
 'AS Saint-Etienne': 'Saint-Etienne',
 'EA Guingamp': 'Guingamp',
 'SM Caen': 'Caen',
 'UD Almeria': 'Almeria',
 'SD Eibar': 'Eibar',
 'SD Huesca': 'Huesca',
 'Cordoba CF': 'Cordoba',
 'Sporting Gijon': 'Sporting Gijon',
 'Real Valladolid CF': 'Real Valladolid',
 'Malaga CF': 'Malaga',
 'Wycombe Wanderers': 'Wycombe',
 'Burton Albion': 'Burton Albion',
 'Crewe Alexandra': 'Crewe Alexandra',
 'Swindon Town': 'Swindon',
 'Colchester United': 'Colchester',
 'Peterborough United': 'Peterborough',
 'Gillingham FC': 'Gillingham',
 'Southend United': 'Southend',
 'Milton Keynes Dons': 'MK Dons',
 'Oldham Athletic': 'Oldham Athletic',
 'Yeovil Town': 'Yeovil Town',
 'Bradford City': 'Bradford City',
 'Scunthorpe United': 'Scunthorpe',
 'MSV Duisburg': 'Duisburg',
 'SpVgg Greuther Furth': 'Greuther Furth',
 'Zenit St. Petersburg': 'Zenit',
 'Eintracht Braunschweig': 'Braunschweig',
 'FC Hansa Rostock': 'Hansa Rostock',
 'US Salernitana': 'Salernitana',
 'SPAL': 'SPAL',
 'Wimbledon FC': 'Wimbledon',
 'Middlesbrough FC': 'Middlesbrough'}

